

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL.VideoJuegos
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class VideoJuegosDatabaseEntities : DbContext
{
    public VideoJuegosDatabaseEntities()
        : base("name=VideoJuegosDatabaseEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Categoria> Categoria { get; set; }

    public DbSet<Consola> Consola { get; set; }

    public DbSet<Producto> Producto { get; set; }

    public DbSet<ProductoConsola> ProductoConsola { get; set; }

    public DbSet<Renta> Renta { get; set; }

    public DbSet<TipoRenta> TipoRenta { get; set; }

    public DbSet<Usuario> Usuario { get; set; }

    public DbSet<Cliente> Cliente { get; set; }

}

}

