
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL.VideoJuegos
{

using System;
    using System.Collections.Generic;
    
public partial class ProductoConsola
{

    public ProductoConsola()
    {

        this.Renta = new HashSet<Renta>();

    }


    public int Id { get; set; }

    public int CodigoProducto { get; set; }

    public int CodigoConsola { get; set; }

    public int Existencia { get; set; }

    public int Disponibilidad { get; set; }



    public virtual Consola Consola { get; set; }

    public virtual Producto Producto { get; set; }

    public virtual ICollection<Renta> Renta { get; set; }

}

}
