
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL.VideoJuegos
{

using System;
    using System.Collections.Generic;
    
public partial class ProductoConsola
{

    public ProductoConsola()
    {

        this.Renta = new HashSet<Renta>();

    }


    public int Id { get; set; }

    public int CodigoProducto { get; set; }

    public int CodigoConsola { get; set; }

    public int Existencia { get; set; }



    public virtual Consola Consola { get; set; }

    public virtual Producto Producto { get; set; }

    public virtual ICollection<Renta> Renta { get; set; }

}

}
