
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL.VideoJuegos
{

using System;
    using System.Collections.Generic;
    
public partial class Renta
{

    public int Id { get; set; }

    public int CodigoProductoConsola { get; set; }

    public System.DateTime Fecha { get; set; }

    public int CodigoTipoRenta { get; set; }

    public decimal PrecioRenta { get; set; }

    public string TipoDocumento { get; set; }

    public int CodigoCliente { get; set; }



    public virtual ProductoConsola ProductoConsola { get; set; }

    public virtual TipoRenta TipoRenta { get; set; }

    public virtual Cliente Cliente { get; set; }

}

}
