
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL.VideoJuegos
{

using System;
    using System.Collections.Generic;
    
public partial class Renta
{

    public int Id { get; set; }

    public int CodigoProductoConsola { get; set; }

    public System.DateTime Fecha { get; set; }

    public int CodigoTipoRenta { get; set; }

    public decimal PrecioRenta { get; set; }

    public string Documento { get; set; }

    public string TipoDocumento { get; set; }

    public int CodigoCliente { get; set; }



    public virtual ProductoConsola ProductoConsola { get; set; }

    public virtual TipoRenta TipoRenta { get; set; }

    public virtual Cliente Cliente { get; set; }

}

}
