
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL.VideoJuegos
{

using System;
    using System.Collections.Generic;
    
public partial class TipoRenta
{

    public TipoRenta()
    {

        this.Renta = new HashSet<Renta>();

    }


    public int Id { get; set; }

    public string Descripcion { get; set; }

    public decimal Precio { get; set; }



    public virtual ICollection<Renta> Renta { get; set; }

}

}
